services:
  api:
    container_name: statuspage-api
    env_file: ".env"
    build:
      context: .
      dockerfile: ./api/Dockerfile
    depends_on:
      db:
        condition: service_healthy
    ports:
      - 8080:8080
    volumes:
      - $KUBECONFIG:$KUBECONFIG
      - ./api/src/:/app
    networks:
      - app-network
  db:
    image: timescale/timescaledb:2.16.1-pg16
    container_name: statuspage-db
    restart: always
    environment:
      POSTGRES_USER: statuspage
      POSTGRES_PASSWORD: statuspage
      POSTGRES_DB: statuspage
    volumes:
      - ./db:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U statuspage"]
      interval: 3s
      timeout: 3s
      retries: 3
    ports:
      - 5432:5432
    networks:
      - app-network
  app:
    container_name: statuspage-app
    image: oven/bun:1.1
    ports:
      - 3000:3000
    volumes:
      - ./app:/app
    working_dir: /app
    entrypoint: /app/entrypoint.sh
    networks:
      - app-network
    depends_on:
      - api

networks:
  app-network:
